cursor            {{ colors.primary }}
cursor_text_color {{ colors.on_primary }}

foreground            {{ colors.terminal.foreground }}
background            {{ colors.terminal.background }}
selection_foreground  {{ colors.terminal.selectionFg }}
selection_background  {{ colors.terminal.selectionBg }}
url_color             {{ colors.secondary }}

# normal
color0  {{ colors.terminal.normal.black }}
color1  {{ colors.terminal.normal.red }}
color2  {{ colors.terminal.normal.green }}
color3  {{ colors.terminal.normal.yellow }}
color4  {{ colors.terminal.normal.blue }}
color5  {{ colors.terminal.normal.magenta }}
color6  {{ colors.terminal.normal.cyan }}
color7  {{ colors.terminal.normal.white }}

# bright
color8  {{ colors.terminal.bright.black }}
color9  {{ colors.terminal.bright.red }}
color10 {{ colors.terminal.bright.green }}
color11 {{ colors.terminal.bright.yellow }}
color12 {{ colors.terminal.bright.blue }}
color13 {{ colors.terminal.bright.magenta }}
color14 {{ colors.terminal.bright.cyan }}
color15 {{ colors.terminal.bright.white }}

active_tab_foreground {{ colors.on_primary }}
active_tab_background {{ colors.primary }}
inactive_tab_foreground {{ colors.on_surface_variant }}
inactive_tab_background {{ colors.surface_variant }}

active_border_color {{ colors.primary }}
inactive_border_color {{ colors.outline }}
