-- Generated by Matugen (themed)
require("mini.base16").setup({
	palette = {
		base00 = "{{ colors.terminal.background }}",
		base01 = "{{ colors.surface_variant }}",
		base02 = "{{ colors.terminal.normal.black }}",
		base03 = "{{ colors.on_surface_variant }}",
		base04 = "{{ colors.outline }}",
		base05 = "{{ colors.terminal.foreground }}",
		base06 = "{{ colors.terminal.normal.white }}",
		base07 = "{{ colors.terminal.bright.white }}",
		base08 = "{{ colors.terminal.normal.red }}",
		base09 = "{{ colors.terminal.bright.red }}",
		base0A = "{{ colors.terminal.normal.yellow }}",
		base0B = "{{ colors.terminal.normal.green }}",
		base0C = "{{ colors.terminal.normal.cyan }}",
		base0D = "{{ colors.terminal.normal.blue }}",
		base0E = "{{ colors.terminal.normal.magenta }}",
		base0F = "{{ colors.terminal.bright.black }}",
	},
	use_cterm = true,
})

require("mini.hues").setup({
	background = "{{ colors.surface }}",
	foreground = "{{ colors.on_surface }}",
})

local function set_hl(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

set_hl({
	"Normal",
	"NormalNC",
	"SignColumn",
	"LineNr",
	"EndOfBuffer",
	"StatusLine",
	"StatusLineNC",
	"lualine",
}, {
	bg = "{{ colors.surface }}",
})

set_hl({
	"MiniFilesBorder",
	"MiniFilesNormal",
	"MiniFilesTitle",
	"MiniPickBorder",
	"MiniPickBorderBusy",
	"MiniPickBorderText",
	"MiniPickHeader",
	"MiniPickPrompt",
	"MiniPickPromptCaret",
	"MiniPickPromptCaret",
	"MiniPickPreviewRegion",
	"MiniPickNormal",
	"MiniPickPromptPrefix",
}, {
	fg = "{{ colors.on_surface }}",
})

set_hl({ "Type", "TSType", "@type", "String", "TSString", "TSMethod", "Method" }, {
	fg = "{{ colors.tertiary }}",
})

set_hl({ "TSComment", "Comment" }, {
	fg = "{{ colors.outline }}",
	italic = true,
})

set_hl({ "TSFunction", "Function" }, {
	fg = "{{ colors.secondary }}",
})

set_hl({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "{{ colors.primary }}",
})

-- Bufferline
local function set_bufferline_highlights()
	local ok, bufferline = pcall(require, "bufferline")
	if ok then
		bufferline.setup({
			highlights = {
				-- fill = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
				-- background = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
				-- buffer_visible = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface }}" },
				-- separator = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.outline }}" },
				buffer_selected = {
					bg = "{{ colors.surface }}",
					fg = "{{ colors.tertiary }}",
					bold = true,
				},
			},
		})
	end
end

vim.defer_fn(set_bufferline_highlights, 100)
vim.api.nvim_create_autocmd("ColorScheme", {
	pattern = "*",
	callback = set_bufferline_highlights,
})

-- Lualine theme
local lualine_theme = {
	normal = {
		a = { bg = "{{ colors.primary }}", fg = "{{ colors.on_primary }}", gui = "bold" },
		b = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface }}" },
		c = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
	},
	insert = {
		a = { bg = "{{ colors.secondary }}", fg = "{{ colors.on_secondary }}", gui = "bold" },
		b = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface }}" },
		c = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
	},
	visual = {
		a = { bg = "{{ colors.tertiary }}", fg = "{{ colors.on_tertiary }}", gui = "bold" },
		b = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface }}" },
		c = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
	},
	replace = {
		a = { bg = "{{ colors.error }}", fg = "{{ colors.on_error }}", gui = "bold" },
		b = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface }}" },
		c = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
	},
	command = {
		a = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface_variant }}", gui = "bold" },
		b = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.on_surface }}" },
		c = { bg = "{{ colors.surface }}", fg = "{{ colors.on_surface }}" },
	},
	inactive = {
		a = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.outline }}", gui = "bold" },
		b = { bg = "{{ colors.surface_variant }}", fg = "{{ colors.outline }}" },
		c = { bg = "{{ colors.surface }}", fg = "{{ colors.outline }}" },
	},
}

require("lualine").setup({
	options = { theme = lualine_theme },
})

vim.api.nvim_set_hl(0, "MiniStarterAccent", { fg = "{{ colors.primary }}" })
vim.api.nvim_set_hl(0, "MiniStarterHeader", { fg = "{{ colors.secondary }}" })

local splits = {
	{ "        ╭╮╭┬─╮╭─╮", "┬  ┬┬╭┬╮", "┐ ╭─┬─╮   ┬ " },
	{ "        │││├┤ │ │", "╰┐┌╯││││", "├──╮│ │ ┬ │" },
	{ "        ╯╰╯╰─╯╰─╯", " ╰╯ ┴┴ ┴", "╰──╯┴ ╰─┴─╯" },
}

local art = [[
        ╭╮╭┬─╮╭─╮┬  ┬┬╭┬╮┐ ╭─┬─╮   ┬ 
        │││├┤ │ │╰┐┌╯││││├──╮│ │ ┬ │
        ╯╰╯╰─╯╰─╯ ╰╯ ┴┴ ┴╰──╯┴ ╰─┴─╯
]]

local starter = require("mini.starter")
starter.setup({
	evaluate_single = true,
	header = art,
	footer = art,
	items = {
		-- Use this if you set up 'mini.sessions'
		starter.sections.sessions(1, true),
		-- starter.sections.pick(),
		starter.sections.recent_files(5, true, false),
		starter.sections.builtin_actions(),
	},
	content_hooks = {
		starter.gen_hook.adding_bullet(),
		starter.gen_hook.indexing("all", { "Builtin actions" }),
		starter.gen_hook.aligning("center", "center"),
		function(content)
			local h_idx, f_idx = 0, #splits + 1
			for _, line in ipairs(content) do
				local new = {}
				for _, unit in ipairs(line) do
					if unit.type == "header" then
						h_idx = h_idx + 1
						local sp = splits[h_idx]
						if sp and unit.string == table.concat(sp) then
							vim.list_extend(new, {
								{ string = sp[1], type = "header", hl = "MiniStarterHeader" },
								{ string = sp[2], type = "header", hl = "MiniStarterAccent" },
								{ string = sp[3], type = "header", hl = "MiniStarterHeader" },
							})
						else
							table.insert(new, unit)
						end
					elseif unit.type == "footer" then
						f_idx = f_idx - 1
						local sp = splits[f_idx]
						if sp and unit.string == table.concat(sp) then
							vim.list_extend(new, {
								{ string = sp[1], type = "footer", hl = "MiniStarterFooter" },
								{ string = sp[2], type = "footer", hl = "MiniStarterAccent" },
								{ string = sp[3], type = "footer", hl = "MiniStarterFooter" },
							})
						else
							table.insert(new, unit)
						end
					else
						table.insert(new, unit)
					end
				end
				for i = #line, 1, -1 do
					line[i] = nil
				end
				for _, u in ipairs(new) do
					table.insert(line, u)
				end
			end
			return content
		end,
	},
})
